# Generated by Django 5.0.1 on 2024-02-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymanagement',
            name='composition',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='inventorymanagement',
            name='exp_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inventorymanagement',
            name='mfg_date',
            field=models.DateField(),
        ),
    ]
