# Generated by Django 5.0.1 on 2024-02-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_inventorymanagement_composition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('composition', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=122)),
                ('order_date', models.DateField()),
            ],
        ),
    ]
